### ISSUE TITLE
好像没办法收取附件跟拉取那些HTML带图片的邮件

### ISSUE THREAD

**Issue by Bondig** [zhouzhongguang/ZGMailbox#1]
好像没办法收取附件跟拉取那些HTML带图片的邮件

**Comment by zhouzhongguang** [comment]
我这边是可以的、你把具体情况描述一下、我找个时间看下

**Comment by Bondig** [comment]
就是我把你的代码clone下来,跑着运行起来了,在登录了邮箱之后,比如有图片的邮件都是显示空白,而且有附件的邮件,点击就闪退,然后报错Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSTaggedPointerString stringByAppendingString:]: nil argument,然后我看了下你的代码,发现有些在MailAttachment文件夹里,Manager跟Models这2个文件夹是空的,不知道是你忘记上传了,还是本身这里就没有代码的.

**Comment by zhouzhongguang** [comment]
那些空的就是没有文件的、回头我优化下

你说的问题、我晚上找个时间看下

**Comment by Bondig** [comment]
好的,不过好像测试了下QQ邮箱倒是能成功登陆,如果换成163邮箱的话,用授权码登陆,有的邮箱就可以登陆成功,有的就提示密码错误,不知道是163的问题,还是什么问题,我也在看你的代码,看下怎么解决
